[build]
  base = "client"
  command = "npm run build"
  publish = "dist"
  functions = "../server/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"
  functions = "../server/functions"
  functionsPort = 9999

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 